/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Core.Database;
import UIResource.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angga
 */
public final class Amenities extends javax.swing.JFrame {

    /**
     * Creates new form Amenities
     */
    private final Connection conn;
    private PreparedStatement ps;
    private ResultSet rs;
    private final DefaultTableModel tb_model;
    
    public String room;
    public String roomId;
    
    public Amenities(String id, String room) {
        initComponents();
        conn = (Connection) Database.Connect();
        tb_model = (DefaultTableModel) amenitiesTable.getModel();
        roomText.setText(room);
        this.room = room;
        this.roomId = id;
        
        // amenity list
        getAmenitiesListCombo();
        getAmenitiesRoom();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }
    
    public void getAmenitiesListCombo(){
        try {
            String query = "SELECT * from amenities a where a.id not in "
                    + "(SELECT amenityId from roomamenity left join rooms on rooms.id=roomamenity.roomId "
                    + "WHERE roomNumber = ?)";
            ps = conn.prepareStatement(query);
            ps.setString(1, room);
            rs = ps.executeQuery();
            tb_model.setNumRows(0);
            int rows = 0;
            amenityCombo.removeAllItems();
            while(rs.next()){
                amenityCombo.addItem(rs.getString("id")+"-"+rs.getString("amenityName"));
                rows++;
            }
            if(rows==0){
                amenityCombo.addItem("");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void getAmenitiesRoom(){
        try {
            String query = "SELECT amenities.amenityName as name FROM roomamenity "
                    + "INNER JOIN amenities ON amenities.id=roomamenity.amenityId "
                    + "INNER JOIN rooms on rooms.id=roomamenity.roomId where rooms.roomNumber=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, room);
            rs = ps.executeQuery();
            tb_model.setNumRows(0);
            int no = 1;
            while(rs.next()){
                Object data[] = {
                    no,
                    rs.getString("name"),
                    "Available",
                    "Standart",
                };
                tb_model.addRow(data);
                no++;
            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addAmenity = new javax.swing.JButton();
        amenityCombo = new javax.swing.JComboBox();
        spTable = new javax.swing.JScrollPane();
        amenitiesTable = new UIResource.Table();
        jPanel4 = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        roomText = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Amenities");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addAmenity.setBackground(new java.awt.Color(230, 155, 6));
        addAmenity.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        addAmenity.setForeground(new java.awt.Color(255, 255, 255));
        addAmenity.setText("Add New");
        addAmenity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAmenityActionPerformed(evt);
            }
        });
        jPanel1.add(addAmenity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 32));

        amenityCombo.setBackground(new java.awt.Color(230, 155, 6));
        amenityCombo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        amenityCombo.setForeground(new java.awt.Color(255, 255, 255));
        amenityCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amenityComboActionPerformed(evt);
            }
        });
        jPanel1.add(amenityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 192, 32));

        amenitiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "Status", "Type"
            }
        ));
        amenitiesTable.setFillsViewportHeight(true);
        amenitiesTable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        spTable.setViewportView(amenitiesTable);

        jPanel1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 480, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 520, 300));

        jPanel4.setBackground(new java.awt.Color(230, 155, 6));
        jPanel4.setPreferredSize(new java.awt.Dimension(940, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phome.setBackground(new java.awt.Color(230, 155, 6));
        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phomeMouseClicked(evt);
            }
        });
        phome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("<");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        phome.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel4.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        roomText.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        roomText.setForeground(new java.awt.Color(255, 255, 255));
        roomText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roomText.setText("000");
        jPanel4.add(roomText, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 180, 60));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Amenities Room ");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 270, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAmenityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAmenityActionPerformed
        // TODO add your handling code here:
        String[] id = amenityCombo.getSelectedItem().toString().split("-");
        String query = "INSERT INTO roomamenity VALUES(null,?,?)";
        try {
            ps = conn.prepareStatement(query);
            ps.setString(1, roomId);
            ps.setString(2, id[0]);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Room Amenity has successfull added!");
                getAmenitiesListCombo();
                getAmenitiesRoom();
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Insert failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addAmenityActionPerformed

    private void amenityComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amenityComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amenityComboActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        //Home ad = new Home();
        //ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(230,155,6));
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(255, 255, 255));
        phome.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        phome.setBackground(Color.orange);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        // TODO add your handling code here:
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseReleased

    private void phomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Amenities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAmenity;
    private UIResource.Table amenitiesTable;
    private javax.swing.JComboBox amenityCombo;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel phome;
    private javax.swing.JLabel roomText;
    private javax.swing.JScrollPane spTable;
    // End of variables declaration//GEN-END:variables
}
