/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Core.Database;
import UIResource.ScrollBar;
import Views.Users.MasterUser;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.*;

/**
 *
 * @author angga, unggulks
 */
public class Home extends javax.swing.JFrame {
    /**
     * Creates new form Home
     */
    private final DefaultTableModel tb_model1;
    private final DefaultTableModel tb_model2;
    private static Connection conn;
    private static PreparedStatement ps;
    private static Statement stm;
    private static ResultSet rs;
    private final String userid;
    
    public Home(String fullname, String id) {
        initComponents();
        setLocationRelativeTo(null);//Posisi program ditengah windows
        tb_model1 = (DefaultTableModel) table1.getModel();
        tb_model2 = (DefaultTableModel) table2.getModel();
        
        //edit jtabel bawaan ribet, ga jalan, comment dulu
        //JTableHeader hcheckin = checkin.getTableHeader();
        //DefaultTableCellRenderer hcheckin = new DefaultTableCellRenderer(); 
        //checkin.getTableHeader().setOpaque(false);
        //hcheckin.setBackground(new java.awt.Color(230,155,6));
        //hcheckin.setForeground(new java.awt.Color(255, 255, 255));
        //checkin.setPreferredSize(new Dimension(10,30));
        //checkin.getTableHeader().setDefaultRenderer(hcheckin);
        //checkout.getTableHeader().setDefaultRenderer(hcheckin);
        
        //ini buat edit scroll bar
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        spTable2.setVerticalScrollBar(new ScrollBar());
        spTable2.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable2.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        spTable2.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        if (fullname != "")
        {
            user.setText(fullname);
        }
        userid = id;
       
        
        refresh();
        delay();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pusers = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        phome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        plogout = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        pbookings = new javax.swing.JPanel();
        bookings = new javax.swing.JLabel();
        pnewbookings = new javax.swing.JPanel();
        newbookings = new javax.swing.JLabel();
        prooms = new javax.swing.JPanel();
        rooms = new javax.swing.JLabel();
        proomservices = new javax.swing.JPanel();
        roomservices = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        signup = new javax.swing.JLabel();
        signup1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        spTable = new javax.swing.JScrollPane();
        table1 = new UIResource.Table();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        spTable2 = new javax.swing.JScrollPane();
        table2 = new UIResource.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BOOKINGS HOME");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(230, 155, 6));
        jPanel4.setPreferredSize(new java.awt.Dimension(940, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pusers.setBackground(new java.awt.Color(230, 155, 6));
        pusers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pusersMouseClicked(evt);
            }
        });
        pusers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setBackground(new java.awt.Color(255, 255, 255));
        user.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Users");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userMouseReleased(evt);
            }
        });
        pusers.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

        jPanel4.add(pusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 240, 60));

        phome.setBackground(new java.awt.Color(230, 155, 6));
        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phomeMouseClicked(evt);
            }
        });
        phome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        phome.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        jPanel4.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 60));

        plogout.setBackground(new java.awt.Color(230, 155, 6));
        plogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plogoutMouseClicked(evt);
            }
        });
        plogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Storage/logout resized.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMouseReleased(evt);
            }
        });
        plogout.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel4.add(plogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 60, 60));

        pbookings.setBackground(new java.awt.Color(230, 155, 6));
        pbookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pbookingsMouseClicked(evt);
            }
        });
        pbookings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookings.setBackground(new java.awt.Color(255, 255, 255));
        bookings.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        bookings.setForeground(new java.awt.Color(255, 255, 255));
        bookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookings.setText("Bookings");
        bookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bookingsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bookingsMouseReleased(evt);
            }
        });
        pbookings.add(bookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        jPanel4.add(pbookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 100, 60));

        pnewbookings.setBackground(new java.awt.Color(230, 155, 6));
        pnewbookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnewbookingsMouseClicked(evt);
            }
        });
        pnewbookings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newbookings.setBackground(new java.awt.Color(255, 255, 255));
        newbookings.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        newbookings.setForeground(new java.awt.Color(255, 255, 255));
        newbookings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newbookings.setText("New Bookings");
        newbookings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newbookingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newbookingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newbookingsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newbookingsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newbookingsMouseReleased(evt);
            }
        });
        pnewbookings.add(newbookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jPanel4.add(pnewbookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 140, 60));

        prooms.setBackground(new java.awt.Color(230, 155, 6));
        prooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proomsMouseClicked(evt);
            }
        });
        prooms.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rooms.setBackground(new java.awt.Color(255, 255, 255));
        rooms.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        rooms.setForeground(new java.awt.Color(255, 255, 255));
        rooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rooms.setText("Rooms");
        rooms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roomsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomsMouseReleased(evt);
            }
        });
        prooms.add(rooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 60));

        jPanel4.add(prooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 100, 60));

        proomservices.setBackground(new java.awt.Color(230, 155, 6));
        proomservices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proomservicesMouseClicked(evt);
            }
        });
        proomservices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roomservices.setBackground(new java.awt.Color(255, 255, 255));
        roomservices.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        roomservices.setForeground(new java.awt.Color(255, 255, 255));
        roomservices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomservices.setText("Room Services");
        roomservices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomservicesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomservicesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomservicesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                roomservicesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomservicesMouseReleased(evt);
            }
        });
        proomservices.add(roomservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 60));

        jPanel4.add(proomservices, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 140, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 110, 40));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jTextField9.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField9.setOpaque(false);
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 110, 40));

        signup.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        signup.setForeground(new java.awt.Color(51, 51, 51));
        signup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup.setText("Generate Reports");
        signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupMouseExited(evt);
            }
        });
        jPanel1.add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 40));

        signup1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        signup1.setForeground(new java.awt.Color(51, 51, 51));
        signup1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup1.setText("Refresh Table");
        signup1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signup1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup1MouseExited(evt);
            }
        });
        jPanel1.add(signup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 940, 40));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Storage/room_banner.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 200));

        jPanel8.setBackground(new java.awt.Color(36, 47, 65));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(" Kelompok 5 - Aplikasi Pemesanan Kamar Hotel (Studi Kasus - Hotel Cendrawasih)");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 940, 20));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 47, 65));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Storage/checkin 40x40.png"))); // NOI18N
        jLabel2.setText("Checking In Today");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, 40));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room", "Check Out Date"
            }
        ));
        table1.setFillsViewportHeight(true);
        table1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        spTable.setViewportView(table1);

        jPanel5.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 440, 180));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 470, 280));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 47, 65));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Storage/checkout 40x40.png"))); // NOI18N
        jLabel3.setText("Checking Out Today");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 440, 40));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room", "Check In Date"
            }
        ));
        table2.setFillsViewportHeight(true);
        table2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        spTable2.setViewportView(table2);

        jPanel3.add(spTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 440, 180));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 470, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh(){
        tb_model1.setNumRows(0);
        tb_model2.setNumRows(0);
        Calendar cal=Calendar.getInstance();
        SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
        String hari = format2.format(cal.getTime());
        //tabel 1
        try {
            conn = Database.Connect();
            stm = conn.createStatement();
            rs = stm.executeQuery("select guestName, roomNumber, checkOutDate from bookings a inner join rooms b on a.roomId = b.id where checkInDate = '" + hari + "'");
            while(rs.next()){
                Object data[] = {
                    rs.getString("guestName"),
                    rs.getString("roomNumber"),
                    rs.getString("checkOutDate")
                };
                tb_model1.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
        //tabel 2
        try {
            conn = Database.Connect();
            stm = conn.createStatement();
            rs = stm.executeQuery("select guestName, roomNumber, checkInDate from bookings a inner join rooms b on a.roomId = b.id where checkOutDate = '" + hari + "'");
            while(rs.next()){
                Object data[] = {
                    rs.getString("guestName"),
                    rs.getString("roomNumber"),
                    rs.getString("checkInDate")
                };
                tb_model2.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        // TODO add your handling code here:
        MasterUser ad = new MasterUser(userid);
        ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_userMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
        user.setForeground(new java.awt.Color(230,155,6));
        pusers.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_userMouseEntered

    private void userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseExited
        // TODO add your handling code here:
        user.setForeground(new java.awt.Color(255, 255, 255));
        pusers.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_userMouseExited

    private void userMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMousePressed
        // TODO add your handling code here:
        pusers.setBackground(Color.orange);
    }//GEN-LAST:event_userMousePressed

    private void userMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseReleased
        // TODO add your handling code here:
        pusers.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_userMouseReleased

    private void pusersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pusersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pusersMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        //Home ad = new Home();
        //ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(230,155,6));
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(255, 255, 255));
        phome.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        phome.setBackground(Color.orange);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        // TODO add your handling code here:
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseReleased

    private void phomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phomeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        Login ad = new Login();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        // TODO add your handling code here:
        logout.setForeground(new java.awt.Color(230,155,6));
        plogout.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        // TODO add your handling code here:
        logout.setForeground(new java.awt.Color(255, 255, 255));
        plogout.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMousePressed
        // TODO add your handling code here:
        plogout.setBackground(Color.orange);
    }//GEN-LAST:event_logoutMousePressed

    private void logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseReleased
        // TODO add your handling code here:
        plogout.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_logoutMouseReleased

    private void plogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_plogoutMouseClicked

    private void bookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseClicked
        // TODO add your handling code here:
        Bookings ad = new Bookings();
        ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_bookingsMouseClicked

    private void bookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseEntered
        // TODO add your handling code here:
        bookings.setForeground(new java.awt.Color(230,155,6));
        pbookings.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bookingsMouseEntered

    private void bookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseExited
        // TODO add your handling code here:
        bookings.setForeground(new java.awt.Color(255, 255, 255));
        pbookings.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_bookingsMouseExited

    private void bookingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMousePressed
        // TODO add your handling code here:
        pbookings.setBackground(Color.orange);
    }//GEN-LAST:event_bookingsMousePressed

    private void bookingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingsMouseReleased
        // TODO add your handling code here:
        pbookings.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bookingsMouseReleased

    private void pbookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pbookingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pbookingsMouseClicked

    private void newbookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbookingsMouseClicked
        // TODO add your handling code here:
        NewBooking ad = new NewBooking();
        ad.setVisible(true);
        //dispose();
        refresh();
    }//GEN-LAST:event_newbookingsMouseClicked

    private void newbookingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbookingsMouseEntered
        // TODO add your handling code here:
        newbookings.setForeground(new java.awt.Color(230,155,6));
        pnewbookings.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_newbookingsMouseEntered

    private void newbookingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbookingsMouseExited
        // TODO add your handling code here:
        newbookings.setForeground(new java.awt.Color(255, 255, 255));
        pnewbookings.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_newbookingsMouseExited

    private void newbookingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbookingsMousePressed
        // TODO add your handling code here:
        pnewbookings.setBackground(Color.orange);
    }//GEN-LAST:event_newbookingsMousePressed

    private void newbookingsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newbookingsMouseReleased
        // TODO add your handling code here:
        pnewbookings.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_newbookingsMouseReleased

    private void pnewbookingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnewbookingsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnewbookingsMouseClicked

    private void roomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseClicked
        // TODO add your handling code here:
        Rooms ad = new Rooms();
        ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_roomsMouseClicked

    private void roomsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseEntered
        // TODO add your handling code here:
        rooms.setForeground(new java.awt.Color(230,155,6));
        prooms.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_roomsMouseEntered

    private void roomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseExited
        // TODO add your handling code here:
        rooms.setForeground(new java.awt.Color(255, 255, 255));
        prooms.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_roomsMouseExited

    private void roomsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMousePressed
        // TODO add your handling code here:
        prooms.setBackground(Color.orange);
    }//GEN-LAST:event_roomsMousePressed

    private void roomsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomsMouseReleased
        // TODO add your handling code here:
        prooms.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_roomsMouseReleased

    private void proomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proomsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_proomsMouseClicked

    private void roomservicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomservicesMouseClicked
        // TODO add your handling code here:
        RoomServices ad = new RoomServices();
        ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_roomservicesMouseClicked

    private void roomservicesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomservicesMouseEntered
        // TODO add your handling code here:
        roomservices.setForeground(new java.awt.Color(230,155,6));
        proomservices.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_roomservicesMouseEntered

    private void roomservicesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomservicesMouseExited
        // TODO add your handling code here:
        roomservices.setForeground(new java.awt.Color(255, 255, 255));
        proomservices.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_roomservicesMouseExited

    private void roomservicesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomservicesMousePressed
        // TODO add your handling code here:
        proomservices.setBackground(Color.orange);
    }//GEN-LAST:event_roomservicesMousePressed

    private void roomservicesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomservicesMouseReleased
        // TODO add your handling code here:
        proomservices.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_roomservicesMouseReleased

    private void proomservicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proomservicesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_proomservicesMouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseClicked
        // TODO add your handling code here:
        Report ad = new Report();
        ad.setVisible(true);
        //dispose();
    }//GEN-LAST:event_signupMouseClicked

    private void signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseEntered
        // TODO add your handling code here:
        signup.setForeground(Color.orange);
    }//GEN-LAST:event_signupMouseEntered

    private void signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMouseExited
        // TODO add your handling code here:
        signup.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_signupMouseExited

    private void signup1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup1MouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_signup1MouseClicked

    private void signup1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup1MouseEntered
        // TODO add your handling code here:
        signup1.setForeground(Color.orange);
    }//GEN-LAST:event_signup1MouseEntered

    private void signup1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup1MouseExited
        // TODO add your handling code here:
        signup1.setForeground(new java.awt.Color(51, 51, 51));
    }//GEN-LAST:event_signup1MouseExited

    public void delay(){
        Thread clock=new Thread(){
        @Override
        public void run(){
            for(;;){
                Calendar cal=Calendar.getInstance();
                SimpleDateFormat format=new SimpleDateFormat("HH:mm:ss");
                SimpleDateFormat format2=new SimpleDateFormat("yyyy-MM-dd");
                jTextField9.setText(format.format(cal.getTime()));
                jTextField3.setText(format2.format(cal.getTime()));
                //refresh();
            try { 
                sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
          }
        }
        };
        clock.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookings;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel newbookings;
    private javax.swing.JPanel pbookings;
    private javax.swing.JPanel phome;
    private javax.swing.JPanel plogout;
    private javax.swing.JPanel pnewbookings;
    private javax.swing.JPanel prooms;
    private javax.swing.JPanel proomservices;
    private javax.swing.JPanel pusers;
    private javax.swing.JLabel rooms;
    private javax.swing.JLabel roomservices;
    private javax.swing.JLabel signup;
    private javax.swing.JLabel signup1;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable2;
    private UIResource.Table table1;
    private UIResource.Table table2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
