/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Core.Database;
import UIResource.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

public final class Rooms extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    private final Connection conn;
    private PreparedStatement ps;
    private ResultSet rs;
    private final DefaultTableModel tb_model;
    
    public Rooms() {
        initComponents();
        conn = (Connection) Database.Connect();
        tb_model = (DefaultTableModel) roomstable.getModel();
        getRooms();
        clear();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        children_capacity_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        price_field = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        room_number_field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        adult_capacity_field = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        spTable = new javax.swing.JScrollPane();
        roomstable = new UIResource.Table();
        amenities = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ROOM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(230, 155, 6));
        jPanel4.setPreferredSize(new java.awt.Dimension(940, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phome.setBackground(new java.awt.Color(230, 155, 6));
        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phomeMouseClicked(evt);
            }
        });
        phome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("<");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        phome.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel4.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ROOM");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        children_capacity_field.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        children_capacity_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                children_capacity_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(children_capacity_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 210, 29));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Room Number");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        simpan.setBackground(new java.awt.Color(230, 155, 6));
        simpan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Add New");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 32));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Children Capacity");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 160, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("ADD NEW ROOM");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        price_field.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(price_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, 29));

        delete.setBackground(new java.awt.Color(230, 155, 6));
        delete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 100, 32));

        room_number_field.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(room_number_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 29));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Price");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 116, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Adult Capacity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 157, -1));

        update.setBackground(new java.awt.Color(230, 155, 6));
        update.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, 32));

        adult_capacity_field.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(adult_capacity_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 29));

        clear.setBackground(new java.awt.Color(230, 155, 6));
        clear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 100, 32));

        roomstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Room", "Adult Capacity", "Children Capacity", "Price"
            }
        ));
        roomstable.setFillsViewportHeight(true);
        roomstable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roomstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomstableMouseClicked(evt);
            }
        });
        spTable.setViewportView(roomstable);
        if (roomstable.getColumnModel().getColumnCount() > 0) {
            roomstable.getColumnModel().getColumn(0).setMinWidth(0);
            roomstable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 600, 240));

        amenities.setBackground(new java.awt.Color(230, 155, 6));
        amenities.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        amenities.setForeground(new java.awt.Color(255, 255, 255));
        amenities.setText("Amenities");
        amenities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amenitiesActionPerformed(evt);
            }
        });
        jPanel1.add(amenities, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 100, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String room = room_number_field.getText();
        String adult = adult_capacity_field.getText();
        String children = children_capacity_field.getText();
        String price = price_field.getText();
        int row = roomstable.getSelectedRow();
        // GET VALUE OF INDEX COLUMN
        String primary_key = tb_model.getValueAt(row, 0).toString();
        try {
            String query = "UPDATE rooms SET roomNumber=?,adultCapacity=?,childrenCapacity=?,price=? WHERE roomNumber=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, room);
            ps.setString(2, adult);
            ps.setString(3, children);
            ps.setString(4, price);
            ps.setString(5, primary_key);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
                getRooms();
                clear();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Update failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        String id = getRandomString(5);
        String room = room_number_field.getText();
        String adult = adult_capacity_field.getText();
        String children = children_capacity_field.getText();
        String price = price_field.getText();
        // Validasi
        if(room.isEmpty() || adult.isEmpty() || children.isEmpty() || price.isEmpty()){
            JOptionPane.showMessageDialog(null, "Input tidak boleh kosong","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        String query = "INSERT INTO rooms VALUES(?,?,?,?,?)";
        try {
            ps = conn.prepareStatement(query);
            ps.setString(1, "R-"+id);
            ps.setString(2, room);
            ps.setInt(3, Integer.parseInt(adult));
            ps.setInt(4, Integer.parseInt(children));
            ps.setInt(5, Integer.parseInt(price));
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Room has successfull added!");
                getRooms();
                clear();
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Insert failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int row = roomstable.getSelectedRow();
        
        if(row < 0){
            return;
        }
        
        String value = tb_model.getValueAt(row, 0).toString();
        
        // CONFIRM DELETE
        int del = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", value, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(del != 0){
            return;
        }
        
        try {
            String query = "DELETE FROM rooms WHERE roomNumber=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, value);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                getRooms();
                clear();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Delete failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        //Home ad = new Home();
        //ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(230,155,6));
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(255, 255, 255));
        phome.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        phome.setBackground(Color.orange);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        // TODO add your handling code here:
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseReleased

    private void phomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phomeMouseClicked

    private void roomstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomstableMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = roomstable.getSelectedRow();
        if(selectedRowIndex >= 0){
            update.setVisible(true);
            delete.setVisible(true);
            clear.setVisible(true);
            amenities.setVisible(true);
            room_number_field.setText(tb_model.getValueAt(selectedRowIndex, 0).toString());
            adult_capacity_field.setText(tb_model.getValueAt(selectedRowIndex, 1).toString());
            children_capacity_field.setText(tb_model.getValueAt(selectedRowIndex, 2).toString());
            price_field.setText(tb_model.getValueAt(selectedRowIndex, 3).toString());
        }
    }//GEN-LAST:event_roomstableMouseClicked

    private void children_capacity_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_children_capacity_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_children_capacity_fieldActionPerformed

    private void amenitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amenitiesActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = roomstable.getSelectedRow();
        Amenities am = new Amenities(tb_model.getValueAt(selectedRowIndex, 0).toString(),tb_model.getValueAt(selectedRowIndex, 1).toString());
        am.setVisible(true);
    }//GEN-LAST:event_amenitiesActionPerformed
    
    public String getRandomString(int length){
        String str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for(int i = 0; i < length; i++){
                int index = random.nextInt(str.length());
                char randomChar = str.charAt(index);
                sb.append(randomChar);
        }
        String randomString = sb.toString();
        return randomString;
    }
    
    public void getRooms(){
        tb_model.setNumRows(0);
        try {
            Statement stm = conn.createStatement();
            rs = stm.executeQuery("SELECT * FROM rooms ORDER BY roomNumber ASC");
            while(rs.next()){
                Object data[] = {
                    rs.getString("id"),
                    rs.getString("roomNumber"),
                    rs.getInt("adultCapacity"),
                    rs.getInt("childrenCapacity"),
                    rs.getInt("price"),
                };
                tb_model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void clear(){
        update.setVisible(false);
        delete.setVisible(false);
        clear.setVisible(false);
        amenities.setVisible(false);
        room_number_field.setText(null);
        adult_capacity_field.setText(null);
        children_capacity_field.setText(null);
        price_field.setText(null);
        roomstable.getSelectionModel().clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Rooms().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adult_capacity_field;
    private javax.swing.JButton amenities;
    private javax.swing.JTextField children_capacity_field;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel phome;
    private javax.swing.JTextField price_field;
    private javax.swing.JTextField room_number_field;
    private UIResource.Table roomstable;
    private javax.swing.JButton simpan;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
