/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views.Users;

import Views.*;
import Core.Database;
import UIResource.ScrollBar;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;

public final class MasterUser extends javax.swing.JFrame {

    /**
     * Creates new form Rooms
     */
    private final Connection conn;
    private PreparedStatement ps;
    private ResultSet rs;
    private final DefaultTableModel tb_model;
    private String valuserid;
    
    public MasterUser(String id) {
        initComponents();
        conn = (Connection) Database.Connect();
        tb_model = (DefaultTableModel) roomstable.getModel();
        
        //clear();
        valuserid = id;
        getDetails(valuserid);
        getUsers();
        
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        this.setLocation(x, y);
        
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        phome = new javax.swing.JPanel();
        home = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        fullname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        password = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        spTable = new javax.swing.JScrollPane();
        roomstable = new UIResource.Table();
        userid = new javax.swing.JLabel();
        level = new javax.swing.JComboBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ROOM");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(230, 155, 6));
        jPanel4.setPreferredSize(new java.awt.Dimension(940, 60));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        phome.setBackground(new java.awt.Color(230, 155, 6));
        phome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phomeMouseClicked(evt);
            }
        });
        phome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("<");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeMouseReleased(evt);
            }
        });
        phome.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 60));

        jPanel4.add(phome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Master Data User");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(570, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fullname.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        jPanel1.add(fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 210, 29));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Username");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));

        simpan.setBackground(new java.awt.Color(230, 155, 6));
        simpan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(255, 255, 255));
        simpan.setText("Add New");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, 32));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Full Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 160, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("User ID :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        delete.setBackground(new java.awt.Color(230, 155, 6));
        delete.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, 32));

        username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 210, 29));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Level");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 116, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 157, -1));

        update.setBackground(new java.awt.Color(230, 155, 6));
        update.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 100, 32));

        password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 29));

        clear.setBackground(new java.awt.Color(230, 155, 6));
        clear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 100, 32));

        roomstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Full Name", "Password", "Level"
            }
        ));
        roomstable.setFillsViewportHeight(true);
        roomstable.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        roomstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomstableMouseClicked(evt);
            }
        });
        spTable.setViewportView(roomstable);

        jPanel1.add(spTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 530, 220));

        userid.setBackground(new java.awt.Color(204, 255, 102));
        userid.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jPanel1.add(userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 100, 23));

        level.setBackground(new java.awt.Color(230, 155, 6));
        level.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        level.setForeground(new java.awt.Color(255, 255, 255));
        level.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Staf", "Guest" }));
        level.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelActionPerformed(evt);
            }
        });
        jPanel1.add(level, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, 32));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String vuserid = userid.getText();
        String vusername = username.getText();
        String vpassword = password.getText();
        String vfullname = fullname.getText();
        String vlevel = level.getSelectedItem().toString();
        int row = roomstable.getSelectedRow();
        // GET VALUE OF INDEX COLUMN
        String primary_key = tb_model.getValueAt(row, 0).toString();
        try {
            String query = "UPDATE users SET username=?,password=?,fullname=?,level=? WHERE id=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, vusername);
            ps.setString(2, vpassword);
            ps.setString(3, vfullname);
            ps.setString(4, vlevel);
            ps.setString(5, vuserid);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil diubah!");
                getUsers();
                clear();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Update failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        MasterUser lg = new MasterUser(valuserid);
        NewUser ad = new NewUser(lg,true);
        ad.setVisible(true);
        //dispose();
        clear();
        getUsers();
    }//GEN-LAST:event_simpanActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int row = roomstable.getSelectedRow();
        
        if(row < 0){
            return;
        }
        
        String value = tb_model.getValueAt(row, 0).toString();
        
        // CONFIRM DELETE
        int del = JOptionPane.showConfirmDialog(null, "Apakah anda yakin?", value, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        
        if(del != 0){
            return;
        }
        
        try {
            String query = "DELETE FROM users WHERE id=?";
            ps = conn.prepareStatement(query);
            ps.setString(1, value);
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
                getUsers();
                clear();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Delete failed",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clearActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        //Home ad = new Home();
        //ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(230,155,6));
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        // TODO add your handling code here:
        home.setForeground(new java.awt.Color(255, 255, 255));
        phome.setBackground(new java.awt.Color(230,155,6));
    }//GEN-LAST:event_homeMouseExited

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        // TODO add your handling code here:
        phome.setBackground(Color.orange);
    }//GEN-LAST:event_homeMousePressed

    private void homeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseReleased
        // TODO add your handling code here:
        phome.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_homeMouseReleased

    private void phomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phomeMouseClicked

    private void roomstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomstableMouseClicked
        // TODO add your handling code here:
        int selectedRowIndex = roomstable.getSelectedRow();
        if(selectedRowIndex >= 0){
            update.setVisible(true);
            delete.setVisible(true);
            clear.setVisible(true);
            userid.setText(tb_model.getValueAt(selectedRowIndex, 0).toString());
            username.setText(tb_model.getValueAt(selectedRowIndex, 1).toString());
            fullname.setText(tb_model.getValueAt(selectedRowIndex, 2).toString());
            password.setText(tb_model.getValueAt(selectedRowIndex, 3).toString());
            //level.setText(tb_model.getValueAt(selectedRowIndex, 4).toString());
            if(null != tb_model.getValueAt(selectedRowIndex, 4).toString())switch (tb_model.getValueAt(selectedRowIndex, 4).toString()) {
                case "Staf":
                    level.setSelectedIndex(0);
                    break;
                case "Guest":
                    level.setSelectedIndex(1);
                    break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_roomstableMouseClicked

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void levelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelActionPerformed

    
    public void getUsers(){
        tb_model.setNumRows(0);
        try {
            Statement stm = conn.createStatement();
            rs = stm.executeQuery("SELECT * FROM users ORDER BY id ASC");
            while(rs.next()){
                Object data[] = {
                    rs.getInt("id"),
                    rs.getString("username"),
                    rs.getString("fullname"),
                    rs.getString("password"),
                    rs.getString("level")
                };
                tb_model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void getDetails(String id){
        try {
            Statement stm = conn.createStatement();
            rs = stm.executeQuery("SELECT * FROM users where id="+id);
            while(rs.next()){
                update.setVisible(true);
                delete.setVisible(true);
                clear.setVisible(true);
                userid.setText(id);
                username.setText(rs.getString("username"));
                password.setText(rs.getString("password"));
                fullname.setText(rs.getString("fullname"));
                if(null != rs.getString("level"))switch (rs.getString("level")) {
                case "Staf":
                    level.setSelectedIndex(0);
                    break;
                case "Guest":
                    level.setSelectedIndex(1);
                    break;
                default:
                break;
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    public void clear(){
        update.setVisible(false);
        delete.setVisible(false);
        clear.setVisible(false);
        userid.setText(null);
        username.setText(null);
        password.setText(null);
        fullname.setText(null);
        level.setSelectedIndex(0);
        roomstable.getSelectionModel().clearSelection();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> {
        //    new MasterUser().setVisible(true);
        //});
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField fullname;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox level;
    private javax.swing.JTextField password;
    private javax.swing.JPanel phome;
    private UIResource.Table roomstable;
    private javax.swing.JButton simpan;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JButton update;
    private javax.swing.JLabel userid;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
